CREATE TABLE IF NOT EXISTS merk (
  id SERIAL PRIMARY KEY,
  nama VARCHAR NOT NULL UNIQUE,
  kode VARCHAR(4) NOT NULL UNIQUE
);

ALTER TABLE produk ADD COLUMN IF NOT EXISTS sku VARCHAR UNIQUE;
ALTER TABLE produk ADD COLUMN IF NOT EXISTS id_merk INT REFERENCES merk(id);

CREATE INDEX IF NOT EXISTS idx_produk_sku ON produk(sku);
CREATE INDEX IF NOT EXISTS idx_produk_id_merk ON produk(id_merk);
